### ISSUE TITLE
Support for M1 Macs?

### ISSUE THREAD

**Issue by torokati44** [osvenskan/posix_ipc#35]
When trying to use this module on macOS on an ARM machine, this test fails on the following line:
https://github.com/osvenskan/posix_ipc/blob/88c384a4d9de3c601a11020dd5fa1971a6ed789a/tests/test_memory.py#L315
With this message: `AssertionError:16384 != 4096`

This is more than likely due to these processors using a 16k page size rather than the more usual 4k. The Asahi Linux community has already written much about this.

**Comment by torokati44** [comment]
I think there might be a confusion here between FS block size and memory page size.
`os.statvfs` returns the file system block size in its first value (`f_bsize`). Shared memory, not being on any real file system on any disk, apparently has not much to do with that.

**Comment by torokati44** [comment]
Not to mention the difference between the physical page size and the page size of the process... :|
See: https://docs.python.org/3/library/resource.html#resource.getpagesize

Either way, if the exact new value of `mem.size` is not that important, only that it's greater than zero (and _perhaps_ that it's a multiple of 1024 or 4096), perhaps the test could be made more lenient.

**Comment by osvenskan** [comment]
Thanks for the bug report! I have an M1 Mac, so I'll be able to experiment with this myself.

**Comment by osvenskan** [comment]
Interestingly, I'm unable to re-create this failure on my system (2021 M1 Pro, OS version 12.6). Can you tell me more about the system where you see this fail?

Also, can you copy/paste the output of this command?

```
python -c "import os; print(os.statvfs('.'))"
```

**Comment by rhornig** [comment]
Actually we are trying to set up the given package with the NIX package manager on an M1 mac and the build f this package fails when it runs the tests. I will try to provide some additional data to reproduce it.

**Comment by tabgab** [comment]
os.statvfs_result(f_bsize=1048576, f_frsize=4096, f_blocks=242837545, f_bfree=142983978, f_bavail=142983978, f_files=1425860975, f_ffree=1424391824, f_favail=1424391824, f_flag=0, f_namemax=255)

**Comment by osvenskan** [comment]
I also want to point out for anyone reading that despite the title of the ticket, `posix_ipc` works just fine on M1 macs except for one test failing due to macOS allocating a larger memory segment than the caller requested.

**Comment by osvenskan** [comment]
@torokati44 @rhornig @tabgab the `develop` branch contains a fixed version of the test if you want to try it out.

**Comment by torokati44** [comment]
Thank you so much, @osvenskan!
Would you be able to push a new release including this fix on PyPI in the near future?
It would make our work a lot easier.

**Comment by osvenskan** [comment]
Yes, I have a new release ready to go, but I was hoping one of you could test it out first since I can't re-create the problem on my Mac. Have you had a chance to test it out? Here's the change that should fix the failing test.

https://github.com/osvenskan/posix_ipc/commit/c505aeaf6d7d37d9d0142a4922d168583bf5dcf6

**Comment by torokati44** [comment]
Yes, I think @rhornig will try it out sometime soon.

**Comment by osvenskan** [comment]
`posix_ipc` 1.1.0 has been released; it contains the fix for this issue. If I don't hear back from anyone I'll assume this issue is resolved and close this soon.

https://pypi.org/project/posix-ipc/1.1.0/

**Comment by rhornig** [comment]
My apologies for the late response. Sadly the change in c505aea did not fix all test failures (only 1 out of 3). I was able to set up the package on my machine and give a proper fix in the above pull request. The main issue was that `mmap` rounds the returned size to the **pagesize** of the OS and not the **filesystem block size**. This was the same on Linux and intel based MACs, but is different on aarch64 macOS machines (pagesize is 16384 here)

**Comment by rhornig** [comment]
Make sure that you **run the tests in arm64 (native) mode**. In i386 mode, the operating system will report back a page size of 4096 and all tests will pass.

**Comment by osvenskan** [comment]
@rhornig Thanks for the update. I finally got a chance to update my Python to arm64 native and I can re-create the problem. I have no doubt your PR fixes it, but I need to figure out how to make sure that change doesn't break on other platforms. Some I can test under AWS EC2 instances, but I lost the ability to test FreeBSD when I moved to an M1 Mac since VirtualBox can't emulate x86 on ARM (yet).

**Comment by osvenskan** [comment]
Notes to myself: I ran the snippet below on several Linux ARM & x86 platforms, an M1 Mac (using ARM-compiled Python), and an x86 Mac (courtesy of a friend) --

```
python3 -c "import os; import mmap; bs = os.statvfs('.')[1]; print(f'block: {bs}'); print(f'page: {mmap.PAGESIZE}')"
```

On all platforms except the M1 Mac, `statvfs()` and `mmap.PAGESIZE` produces the same output --

```
block: 4096
page: 4096
```

Only on M1 Mac w/ARM Python are the values different --

```
block: 4096
page: 16384
```

That suggests #41 is a good fix. I haven't been able to test xBSD yet, nor am I likely to be able to. `:-/` I would also like to test x86 Python on an M1 Mac just to be on the safe side. It's not hard to do, I just need to find the time. Based on previous experience I think it will be the 4096/4096 answer.

**Comment by osvenskan** [comment]
Thanks to a tip from @bpollack I learned that vultr.com has FreeBSD VMs, and I'm happy to report that the test above reports 4096 for both values. 

```
$ uname -a
FreeBSD bsdtest 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64
$ python3 -c "import os; import mmap; bs = os.statvfs('.')[1]; print(f'block: {bs}'); print(f'page: {mmap.PAGESIZE}')"
block: 4096
page: 4096
```

**Comment by osvenskan** [comment]
Confirmed that x86 Python on M1 Mac returns 4096/4096 using the command above.

**Comment by osvenskan** [comment]
Reopening until I release a new version that contains the fix.

**Comment by osvenskan** [comment]
This is fixed in version 1.1.1 which is now released.
